"""``nimkm`` -- an MCP server for the API keys of your own NVIDIA Build/NIM account.

The primary surface is ``nimkm mcp serve``: an MCP client spawns it and talks
JSON-RPC over stdio. ``nimkm mcp setup`` registers that command with the clients
found on this machine. The web dashboard (``nimkm web``) is a separate,
optional administration surface over the same database.

Design notes
------------
* **stdlib only.** The CLI must be able to report a broken installation, so it
  never depends on anything that could itself be broken. Heavy imports (uvicorn,
  SQLAlchemy, the application package) happen inside the commands that need them.
* **Settings are read lazily.** ``app.core.config`` is imported only *after*
  ``config.env`` has been written and after the stdio profile has been applied,
  because instantiating ``Settings`` also builds the database engine downstream.
* **Nothing leaks.** No user-facing string mentions Python, uv, uvicorn or
  FastAPI: from the outside this is one command that speaks MCP.
* **Idempotent.** ``nimkm init`` never overwrites existing secrets unless asked;
  ``nimkm mcp setup`` can be re-run at any time.
"""

from __future__ import annotations

import argparse
import contextlib
import getpass
import json
import os
import secrets
import shutil
import socket
import subprocess
import sys
import threading
import urllib.error
import urllib.request
import webbrowser
from pathlib import Path
from typing import Any

from app import __version__
from app.core import paths

REPO = "BySergiMM/nim-key-manager"
PYPI_PACKAGE = "nim-key-manager"
DOCS_URL = f"https://github.com/{REPO}#readme"

#: ``nimkm mcp setup`` exit code meaning "ran fine, but nothing was connected"
#: (the user declined). Callers such as the installers use it to keep offering
#: the step instead of reporting success.
NOTHING_CHANGED = 2

#: Default bootstrap administrator. ``.internal`` is IANA-reserved for private
#: use, so it can never resolve -- and unlike ``admin@localhost`` it is a valid
#: address, which matters because every API and MCP response validates it.
DEFAULT_ADMIN_EMAIL = "admin@nimkm.internal"

# --------------------------------------------------------------------------- #
# terminal helpers                                                             #
# --------------------------------------------------------------------------- #


def _supports_color() -> bool:
    if os.environ.get("NO_COLOR") or not sys.stdout.isatty():
        return False
    if sys.platform == "win32":  # enable VT sequences on legacy consoles
        try:
            import ctypes

            kernel32 = ctypes.windll.kernel32  # type: ignore[attr-defined]
            kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)
        except Exception:  # pragma: no cover - non-Windows or restricted host
            return False
    return True


_COLOR = _supports_color()


def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _COLOR else text


def bold(text: str) -> str:
    return _c("1", text)


def dim(text: str) -> str:
    return _c("2", text)


def green(text: str) -> str:
    return _c("32", text)


def yellow(text: str) -> str:
    return _c("33", text)


def red(text: str) -> str:
    return _c("31", text)


def cyan(text: str) -> str:
    return _c("36", text)


def say(message: str = "") -> None:
    print(message)


def step(message: str) -> None:
    print(f"{cyan('::')} {message}")


def ok(message: str) -> None:
    print(f"{green('OK')}  {message}")


def warn(message: str) -> None:
    print(f"{yellow('!!')}  {message}")


def fail(message: str) -> None:
    print(f"{red('XX')}  {message}", file=sys.stderr)


# --------------------------------------------------------------------------- #
# configuration file handling                                                  #
# --------------------------------------------------------------------------- #

CONFIG_HEADER = f"""\
# NIM Key Manager -- generated by `nimkm init`.
# Values here are defaults for this machine; real environment variables win.
# Full reference: https://github.com/{REPO}/blob/main/.env.example
"""


def read_config(path: Path | None = None) -> dict[str, str]:
    """Parse ``config.env`` into a mapping (comments and blanks ignored)."""
    path = path or paths.config_file()
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def write_config(values: dict[str, str], path: Path | None = None) -> Path:
    """Write ``config.env`` atomically with owner-only permissions."""
    path = path or paths.config_file()
    path.parent.mkdir(parents=True, exist_ok=True)
    body = CONFIG_HEADER + "\n" + "\n".join(f"{k}={v}" for k, v in values.items()) + "\n"
    tmp = path.with_suffix(".tmp")
    tmp.write_text(body, encoding="utf-8")
    if os.name != "nt":
        os.chmod(tmp, 0o600)
    tmp.replace(path)
    if os.name != "nt":
        os.chmod(path, 0o600)
    return path


def _new_secret() -> str:
    return secrets.token_urlsafe(48)


def _default_config(database_url: str, host: str, port: int) -> dict[str, str]:
    return {
        "ENVIRONMENT": "production",
        "DEBUG": "false",
        "HOST": host,
        "PORT": str(port),
        "DATABASE_URL": database_url,
        "AUTO_CREATE_TABLES": "false",
        "JWT_SECRET": _new_secret(),
        "ENCRYPTION_MASTER_KEY": _new_secret(),
        "MCP_OAUTH_JWT_SIGNING_KEY": _new_secret(),
        "PUBLIC_BASE_URL": f"http://{'127.0.0.1' if host in ('0.0.0.0', '::') else host}:{port}",
        # The connector stays idle until OAuth credentials are provided;
        # `nimkm mcp setup` fills these in.
        "MCP_ENABLED": "true",
        "MCP_AUTH_ENABLED": "true",
        "MCP_AUTH_PROVIDER": "github",
        "MCP_GITHUB_CLIENT_ID": "",
        "MCP_GITHUB_CLIENT_SECRET": "",
        "MCP_ALLOWED_IDENTITIES": "",
    }


# --------------------------------------------------------------------------- #
# small utilities                                                              #
# --------------------------------------------------------------------------- #


def _port_is_free(host: str, port: int) -> bool:
    probe_host = "127.0.0.1" if host in ("0.0.0.0", "::") else host
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(0.6)
        return sock.connect_ex((probe_host, port)) != 0


def _first_free_port(host: str, port: int, attempts: int = 20) -> int:
    for candidate in range(port, port + attempts):
        if _port_is_free(host, candidate):
            return candidate
    return port


def _browsable_url(host: str, port: int) -> str:
    return f"http://{'127.0.0.1' if host in ('0.0.0.0', '::') else host}:{port}"


def _interactive() -> bool:
    return sys.stdin is not None and sys.stdin.isatty()


def _ask(prompt: str) -> str | None:
    """Read a line, or ``None`` when there is nobody to answer.

    ``isatty()`` is not proof that a read will succeed: a console handle
    inherited from a parent that has already closed its input raises EOFError.
    Prompts must degrade to "no answer", never crash the command.
    """
    if not _interactive():
        return None
    try:
        return input(prompt)
    except (EOFError, KeyboardInterrupt):
        say()
        return None


def _run_async(coro: Any) -> Any:
    import asyncio

    if sys.platform == "win32":  # psycopg/asyncpg need the selector loop on Windows
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    return asyncio.run(coro)


def _http_json(url: str, timeout: float = 6.0) -> Any:
    request = urllib.request.Request(url, headers={"Accept": "application/json"})
    with urllib.request.urlopen(request, timeout=timeout) as response:  # noqa: S310
        return json.loads(response.read().decode("utf-8"))


# --------------------------------------------------------------------------- #
# commands                                                                     #
# --------------------------------------------------------------------------- #


def cmd_init(args: argparse.Namespace) -> int:
    home = paths.ensure_dirs()
    config_path = paths.config_file()
    existing = read_config(config_path)

    preserved_master_key: str | None = None
    if existing and args.force:
        backup = config_path.with_suffix(".env.bak")
        shutil.copy2(config_path, backup)
        warn(f"existing configuration backed up to {backup}")
        # Regenerating ENCRYPTION_MASTER_KEY would make every stored API key
        # undecryptable, so it is carried over. There is no safe way to rotate
        # it without re-encrypting the database first.
        preserved_master_key = existing.get("ENCRYPTION_MASTER_KEY") or None
        existing = {}

    if existing:
        step(f"configuration already present at {config_path}")
        values = existing
        host = values.get("HOST", "127.0.0.1")
        port = int(values.get("PORT", "8000"))
    else:
        host = args.host
        port = args.port
        database_url = args.database_url or paths.default_database_url()
        values = _default_config(database_url, host, port)
        if preserved_master_key:
            values["ENCRYPTION_MASTER_KEY"] = preserved_master_key
            say(dim("  keeping the existing ENCRYPTION_MASTER_KEY so stored keys stay readable"))
        write_config(values, config_path)
        ok(f"generated secrets and configuration at {config_path}")

    if args.database_url and values.get("DATABASE_URL") != args.database_url:
        values["DATABASE_URL"] = args.database_url
        write_config(values, config_path)
        ok("database URL updated")

    # Only now is it safe to import anything that reads Settings.
    step("applying database migrations")
    from app.infrastructure.db import migrations

    migrations.upgrade()
    ok(f"database ready ({_describe_database()})")

    created = _ensure_admin(args)
    say()
    say(bold("NIM Key Manager is ready."))
    say(f"  home       {home}")
    say(f"  dashboard  {_browsable_url(host, port)}  {dim('(nimkm web)')}")
    if created:
        email, password = created
        say(f"  admin      {email}")
        if password:
            say(f"  password   {bold(password)}  {dim('(shown once)')}")
    if not args.quiet_next_step:
        say()
        say(f"Connect it to your MCP client with {bold('nimkm mcp setup')}.")
    return 0


def _describe_database() -> str:
    from app.core.config import get_settings

    url = get_settings().database_url
    sqlite_file = paths.sqlite_path(url)
    return f"sqlite {sqlite_file}" if sqlite_file else url.split("@")[-1]


def _ensure_admin(args: argparse.Namespace) -> tuple[str, str | None] | None:
    """Create the first administrator when the user table is empty."""
    from app.application.services.auth_service import AuthService
    from app.domain.enums import Role
    from app.infrastructure.db.repositories import UserRepository
    from app.infrastructure.db.session import SessionFactory

    async def _create() -> tuple[str, str | None] | None:
        async with SessionFactory() as session:
            if await UserRepository(session).count() > 0:
                return None
            email = args.admin_email
            password = args.admin_password
            generated = False
            if not email:
                prompt = f"Administrator e-mail [{DEFAULT_ADMIN_EMAIL}]: "
                answer = None if args.no_input else _ask(prompt)
                email = (answer or "").strip() or DEFAULT_ADMIN_EMAIL
            _require_valid_email(email)
            if not password:
                if not args.no_input and _interactive():
                    with contextlib.suppress(EOFError, KeyboardInterrupt):
                        password = getpass.getpass("Password (empty to generate): ").strip()
                if not password:
                    password = secrets.token_urlsafe(18)
                    generated = True
            await AuthService(session).register(
                email=email, password=password, full_name="Administrator",
                role=Role.ADMIN, actor=None,
            )
            return email, password if generated else None

    return _run_async(_create())


def _require_valid_email(email: str) -> None:
    """Reject an address the API and MCP layers would later refuse to serialise.

    Accounts created here bypass the request schemas, so an address like
    ``admin@localhost`` is accepted at creation and then breaks every response
    that contains the user. Fail here, where it is one clear message.
    """
    from pydantic import BaseModel, EmailStr, ValidationError

    class _Probe(BaseModel):
        email: EmailStr

    try:
        _Probe(email=email)
    except ValidationError as exc:
        reason = exc.errors()[0].get("ctx", {}).get("reason", "not a valid address")
        raise SystemExit(
            f"{red('XX')}  {email!r} cannot be used: {reason}\n"
            f"    Try something like {DEFAULT_ADMIN_EMAIL} or your real address."
        ) from exc


def _startup_blocker(settings: Any) -> str | None:
    """Reason this instance cannot serve, or ``None`` when it is viable.

    A container gets everything from the environment and has no ``config.env``;
    only a machine with *neither* a config file *nor* real secrets is unusable.
    """
    if paths.config_file().exists() or not settings.insecure_defaults():
        return None
    return "no configuration found -- run 'nimkm init' first (or 'nimkm up')."


def cmd_serve(args: argparse.Namespace) -> int:
    from app.core.config import get_settings

    settings = get_settings()
    blocker = _startup_blocker(settings)
    if blocker:
        fail(blocker)
        return 1
    host = args.host or settings.host
    port = args.port or settings.port

    if not _port_is_free(host, port):
        fail(f"port {port} is already in use. Try 'nimkm web --port {port + 1}'.")
        return 1

    import uvicorn

    # ASCII only: Windows consoles default to a legacy code page.
    say(f"{bold('NIM Key Manager')} {__version__}  ->  {cyan(_browsable_url(host, port))}")
    say(dim("dashboard /  |  API docs /docs  |  health /health  |  Ctrl-C to stop"))
    uvicorn.run(
        "app.main:create_asgi_app",
        factory=True,
        host=host,
        port=port,
        reload=args.reload,
        proxy_headers=args.proxy_headers,
        forwarded_allow_ips="*" if args.proxy_headers else None,
        log_config=None,
    )
    return 0


def cmd_up(args: argparse.Namespace) -> int:
    if not paths.config_file().exists():
        init_args = argparse.Namespace(
            force=False, host=args.host or "127.0.0.1", port=args.port or 8000,
            database_url=None, admin_email=None, admin_password=None,
            no_input=args.no_input, quiet_next_step=True,
        )
        code = cmd_init(init_args)
        if code != 0:
            return code
        say()
    else:
        from app.infrastructure.db import migrations

        migrations.upgrade()

    from app.core.config import get_settings

    settings = get_settings()
    host = args.host or settings.host
    port = args.port or settings.port
    if not _port_is_free(host, port):
        new_port = _first_free_port(host, port + 1)
        warn(f"port {port} busy -- using {new_port} instead")
        port = new_port

    if not args.no_browser:
        url = _browsable_url(host, port)
        threading.Timer(1.5, lambda: webbrowser.open(url)).start()

    serve_args = argparse.Namespace(
        host=host, port=port, reload=False, proxy_headers=False
    )
    return cmd_serve(serve_args)


def cmd_migrate(args: argparse.Namespace) -> int:
    from app.infrastructure.db import migrations

    if args.revision == "head":
        migrations.upgrade()
    elif args.downgrade:
        migrations.downgrade(args.revision)
    else:
        migrations.upgrade(args.revision)
    ok(f"database at revision {migrations.head_revision()}")
    return 0


def cmd_doctor(args: argparse.Namespace) -> int:
    checks: list[tuple[str, str, str]] = []  # (level, subject, detail)

    def add(level: str, subject: str, detail: str = "") -> None:
        checks.append((level, subject, detail))

    version = ".".join(str(p) for p in sys.version_info[:3])
    add("ok" if sys.version_info >= (3, 10) else "fail", f"runtime {version}", str(paths.home()))

    _add_client_checks(add)

    config_path = paths.config_file()
    if config_path.exists():
        add("ok", "configuration", str(config_path))
        if os.name != "nt":
            mode = config_path.stat().st_mode & 0o777
            add(
                "ok" if mode == 0o600 else "warn",
                f"config permissions {mode:o}",
                "" if mode == 0o600 else "expected 600; run: chmod 600 " + str(config_path),
            )
    else:
        add("fail", "configuration missing", "run 'nimkm init'")
        _report(checks)
        return 1

    from app.core.config import get_settings

    settings = get_settings()
    insecure = settings.insecure_defaults()
    add(
        "fail" if insecure else "ok",
        "secrets",
        f"{', '.join(insecure)} still using the development placeholder" if insecure else
        "JWT_SECRET and ENCRYPTION_MASTER_KEY are set",
    )

    from app.infrastructure.db import migrations

    try:
        current = _run_async(migrations.current_revision())
        head = migrations.head_revision()
        if current is None:
            add("fail", "database", "reachable but not migrated -- run 'nimkm migrate'")
        elif current != head:
            add("warn", "database", f"at {current}, latest is {head} -- run 'nimkm migrate'")
        else:
            add("ok", "database", f"{_describe_database()} (revision {current})")
    except Exception as exc:  # noqa: BLE001 - diagnostics must not crash
        add("fail", "database unreachable", str(exc).splitlines()[0])

    try:
        from app.infrastructure.db.repositories import UserRepository
        from app.infrastructure.db.session import SessionFactory

        async def _count() -> int:
            async with SessionFactory() as session:
                return await UserRepository(session).count()

        users = _run_async(_count())
        add("ok" if users else "warn", f"{users} user(s)", "" if users else "run 'nimkm init'")
    except Exception as exc:  # noqa: BLE001
        add("warn", "users", str(exc).splitlines()[0])

    free = _port_is_free(settings.host, settings.port)
    add("ok" if free else "warn", f"port {settings.port}",
        "available" if free else "in use (an instance may already be running)")

    # The remote connector is optional; a local-only install is complete without it.
    if not settings.mcp_enabled:
        add("ok", "remote connector", "disabled")
    elif settings.mcp_credentials_configured():
        add("ok", "remote connector", f"{settings.mcp_auth_provider} OAuth configured")
        if not settings.mcp_allowed_identities:
            add("warn", "MCP allow-list empty", "nobody can connect; set MCP_ALLOWED_IDENTITIES")
    else:
        add("ok", "remote connector", "not configured (only needed for remote clients)")

    if not args.offline:
        try:
            request = urllib.request.Request(settings.nvidia_validation_url)
            urllib.request.urlopen(request, timeout=6)  # noqa: S310
            add("ok", "NVIDIA endpoint reachable", settings.nvidia_validation_url)
        except urllib.error.HTTPError as exc:
            level = "ok" if exc.code in (401, 403) else "warn"
            add(level, "NVIDIA endpoint reachable", f"HTTP {exc.code} (auth expected)")
        except Exception as exc:  # noqa: BLE001
            add("warn", "NVIDIA endpoint unreachable", str(exc).splitlines()[0])

    return _report(checks)


def _add_client_checks(add: Any) -> None:
    """Where the MCP server is registered -- the first thing that breaks."""
    from app.mcp import clients

    launcher = _launcher_or_none()
    if launcher is None:
        add("fail", "launcher missing", "reinstall: clients have nothing to run")

    registered: list[tuple[Any, dict[str, Any]]] = []
    for target in clients.discover_targets():
        entry, error = _registration_or_error(target, clients.DEFAULT_SERVER_NAME)
        if error:
            add("warn", f"unreadable client config: {target.label}", error)
        elif entry is not None:
            registered.append((target, entry))

    if not registered:
        detected = [target.label for target in clients.detected_targets()]
        add(
            "warn", "MCP client",
            f"not registered ({', '.join(detected)} detected) -- run 'nimkm mcp setup'"
            if detected else "no MCP client found -- run 'nimkm mcp setup --print'",
        )
        return
    for target, entry in registered:
        stale = launcher is not None and entry.get("command") != launcher
        add(
            "warn" if stale else "ok",
            f"MCP client: {target.label}",
            "points at another install -- run 'nimkm mcp setup'" if stale else str(target.path),
        )


def _report(checks: list[tuple[str, str, str]]) -> int:
    say(bold(f"nimkm {__version__}  |  {paths.home()}"))
    say()
    for level, subject, detail in checks:
        marker = {"ok": green("OK  "), "warn": yellow("WARN"), "fail": red("FAIL")}[level]
        say(f"  {marker}  {subject}{'  ' + dim(detail) if detail else ''}")
    failures = sum(1 for level, _, _ in checks if level == "fail")
    warnings = sum(1 for level, _, _ in checks if level == "warn")
    say()
    if failures:
        say(red(f"{failures} problem(s) need attention."))
        return 1
    say(green("Everything looks good.") if not warnings else yellow(f"{warnings} warning(s)."))
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    """The whole picture: MCP registration first, dashboard second.

    ``nimkm status`` and ``nimkm mcp status`` used to mean different things,
    which is one concept too many for a tool whose main surface is MCP.
    """
    code = cmd_mcp_status(args)
    say()
    say(bold("Dashboard"))
    _say_dashboard_state()
    return code


def _say_dashboard_state() -> None:
    from app.core.config import get_settings

    settings = get_settings()
    url = _browsable_url(settings.host, settings.port)
    try:
        payload = _http_json(f"{url}/health", timeout=3)
    except Exception:  # noqa: BLE001 - any failure means "not running"
        say(f"  {dim('not running')}  {dim(url)} {dim('- start it with nimkm web')}")
        return
    say(f"  {green('running')}  {cyan(url)}")
    say(f"  status {payload.get('status')} · database {payload.get('database')} "
        f"· version {payload.get('version')}")


def cmd_config(args: argparse.Namespace) -> int:
    path = paths.config_file()
    if args.action == "path":
        say(str(path))
        return 0
    if not path.exists():
        fail("no configuration found -- run 'nimkm init' first.")
        return 1
    if args.action == "show":
        values = read_config(path)
        secretish = ("SECRET", "KEY", "PASSWORD", "TOKEN")
        for key, value in values.items():
            masked = value
            if any(word in key for word in secretish) and value:
                masked = value[:4] + "..." + dim("(hidden)")
            say(f"{key}={masked}")
        return 0
    if args.action == "edit":
        editor = os.environ.get("EDITOR") or ("notepad" if os.name == "nt" else "nano")
        return subprocess.call([editor, str(path)])
    # set
    values = read_config(path)
    for assignment in args.assignments:
        if "=" not in assignment:
            fail(f"expected KEY=VALUE, got {assignment!r}")
            return 1
        key, _, value = assignment.partition("=")
        values[key.strip().upper()] = value.strip()
    write_config(values, path)
    ok(f"updated {len(args.assignments)} setting(s) in {path}")
    say(dim("restart the server for changes to take effect"))
    return 0


def cmd_admin(args: argparse.Namespace) -> int:
    from app.application.services.auth_service import AuthService
    from app.core.security import hash_password
    from app.domain.enums import Role
    from app.infrastructure.db.repositories import UserRepository
    from app.infrastructure.db.session import SessionFactory

    async def _list() -> int:
        async with SessionFactory() as session:
            users = await UserRepository(session).list_all()
            if not users:
                warn("no users yet -- run 'nimkm init'")
                return 1
            for user in users:
                flag = "" if user.is_active else dim(" (inactive)")
                say(f"  {user.email:<40} {user.role}{flag}")
            return 0

    async def _create() -> int:
        _require_valid_email(args.email)
        password = args.password or secrets.token_urlsafe(18)
        async with SessionFactory() as session:
            actor = None
            if await UserRepository(session).count() > 0:
                actor = await UserRepository(session).get_by_email(args.actor or "")
                if actor is None or actor.role != Role.ADMIN.value:
                    fail("an existing administrator is required: pass --actor <admin-email>")
                    return 1
            await AuthService(session).register(
                email=args.email, password=password, full_name=args.name,
                role=Role(args.role), actor=actor,
            )
        ok(f"created {args.email} ({args.role})")
        if not args.password:
            say(f"  password  {bold(password)}  {dim('(shown once)')}")
        return 0

    async def _reset() -> int:
        password = args.password or secrets.token_urlsafe(18)
        async with SessionFactory() as session:
            repo = UserRepository(session)
            user = await repo.get_by_email(args.email)
            if user is None:
                fail(f"no user with e-mail {args.email}")
                return 1
            user.hashed_password = hash_password(password)
            await session.commit()
        ok(f"password updated for {args.email}")
        if not args.password:
            say(f"  password  {bold(password)}  {dim('(shown once)')}")
        return 0

    return _run_async({"list": _list, "create": _create, "reset-password": _reset}[args.action]())


# --------------------------------------------------------------------------- #
# MCP: the primary surface                                                     #
# --------------------------------------------------------------------------- #
def cmd_mcp_serve(args: argparse.Namespace) -> int:
    """Speak MCP over stdio. Invoked by the client, not by a human."""
    from app.mcp import stdio

    stdio.prepare_environment(args.identity)
    _ensure_ready_for_stdio()
    return stdio.run(args.identity)


def _ensure_ready_for_stdio() -> None:
    """Self-heal a missing installation so the client never sees a failed start."""
    if paths.config_file().exists():
        return
    paths.ensure_dirs()
    values = _default_config(paths.default_database_url(), "127.0.0.1", 8000)
    write_config(values)
    print(f"initialised a new instance at {paths.home()}", file=sys.stderr)


def cmd_mcp_setup(args: argparse.Namespace) -> int:
    """Register this server with the MCP clients installed on this machine."""
    from app.mcp import clients

    name = args.name
    entry = clients.server_entry()

    if args.print_config:
        say(clients.snippet(name))
        return 0

    if args.scope:
        targets = [clients.target_by_key(args.scope)]
    else:
        targets = clients.detected_targets()
        if not targets:
            warn("no MCP client configuration found on this machine")
            say()
            say("Add this to your client's configuration file:")
            say()
            say(clients.snippet(name))
            say()
            say(dim("or re-run with --scope user|project|desktop to create the file"))
            return 1

    say(bold("Connect NIM Key Manager to your MCP client"))
    say()
    say(f"  command  {cyan(entry['command'])} {' '.join(entry['args'])}")
    say(f"  as       {bold(name)}")
    say()

    changed = 0
    already_connected = 0
    failures = 0
    for target in targets:
        try:
            existing = clients.registration(target, name)
        except clients.ClientConfigError as exc:
            fail(f"{target.label}: {exc}")
            failures += 1
            continue

        if existing == entry:
            ok(f"{target.label} {dim('already up to date')}")
            already_connected += 1
            continue

        say(f"{target.label}")
        say(dim(f"  {target.path}"))
        if existing is None:
            question = f"  Register '{name}' here?"
        else:
            # Do not silently discard a hand-edited entry: show what changes.
            say(dim(f"  currently: {existing.get('command', '?')}"))
            say(dim(f"  will be:   {entry['command']}"))
            question = f"  Replace the existing '{name}' entry?"
        if not _confirm(question, default=True, assume_yes=args.yes):
            say(dim("  skipped"))
            continue

        try:
            outcome = clients.register(target, entry, name)
            # Read it back: a write that "succeeded" but did not land is the one
            # failure the user would otherwise discover inside their AI client.
            if clients.registration(target, name) != entry:
                raise clients.ClientConfigError(
                    "the entry is not in the file after writing it; check "
                    f"{target.path} by hand"
                )
        except clients.ClientConfigError as exc:
            fail(f"  {exc}")
            failures += 1
            continue
        if outcome.backup:
            say(dim(f"  backup: {outcome.backup}"))
        ok(f"  registered  ({target.restart_hint})")
        changed += 1

    if changed:
        say()
        say(bold("Almost there:") + " restart your MCP client, then ask it")
        say(dim('  "list my NVIDIA keys"  or  "dispense a NIM key"'))
    if failures:
        return 1
    if not changed and not already_connected:
        # Nothing was connected -- the installer must keep advertising the step.
        return NOTHING_CHANGED
    return 0


def cmd_mcp_remove(args: argparse.Namespace) -> int:
    from app.mcp import clients

    targets = [clients.target_by_key(args.scope)] if args.scope else clients.detected_targets()
    removed = 0
    failures = 0
    for target in targets:
        try:
            if clients.registration(target, args.name) is None:
                continue
            if not _confirm(f"Remove '{args.name}' from {target.label}?", True, args.yes):
                continue
            outcome = clients.unregister(target, args.name)
        except clients.ClientConfigError as exc:
            fail(f"{target.label}: {exc}")
            failures += 1
            continue
        if outcome.backup:
            say(dim(f"  backup: {outcome.backup}"))
        ok(f"removed from {target.path}")
        removed += 1
    if failures:
        return 1
    if not removed:
        warn(f"'{args.name}' was not registered anywhere")
        return 1
    return 0


def _launcher_or_none() -> str | None:
    """The command clients should run, or ``None`` if it cannot be located."""
    from app.mcp import clients

    try:
        return clients.launcher()
    except clients.ClientConfigError:
        return None


def _registration_or_error(target: Any, name: str) -> tuple[dict[str, Any] | None, str | None]:
    """``(entry, error)`` -- a broken client config must not abort a read-only command."""
    from app.mcp import clients

    if not target.exists:
        return None, None
    try:
        return clients.registration(target, name), None
    except clients.ClientConfigError as exc:
        return None, str(exc)


def cmd_mcp_status(args: argparse.Namespace) -> int:
    from app.mcp import clients

    launcher = _launcher_or_none()
    say(bold("MCP server  ") + dim(f"{launcher} mcp serve" if launcher else "not found"))
    if launcher is None:
        warn("this installation has no launcher on disk; reinstall before registering")
    say()

    say(bold("Clients"))
    any_registered = False
    for target in clients.discover_targets():
        entry, error = _registration_or_error(target, args.name)
        if error:
            say(f"  {red('unreadable')}  {target.label}")
            say(dim(f"              {error}"))
        elif entry is not None:
            any_registered = True
            say(f"  {green('registered')}  {target.label}")
            say(dim(f"              {target.path}"))
            if launcher is not None and entry.get("command") != launcher:
                warn(f"  the registered command differs from this install: {entry.get('command')}")
                say(dim("  run 'nimkm mcp setup' to point it here"))
        elif target.exists:
            say(f"  {dim('detected  ')}  {target.label} {dim('(not registered)')}")
        else:
            say(f"  {dim('not found ')}  {target.label}")
    if not any_registered:
        say()
        say(dim("run 'nimkm mcp setup' to register with the detected clients"))

    from app.core.config import get_settings

    settings = get_settings()
    say()
    say(bold("Remote connector (optional)"))
    if not settings.mcp_enabled:
        say(f"  {dim('disabled')}")
    elif settings.mcp_credentials_configured():
        base = settings.resolve_public_base_url() or _browsable_url(settings.host, settings.port)
        say(f"  {green('configured')}  {base}{settings.mcp_mount_path}")
        say(f"  provider    {settings.mcp_auth_provider}")
        say(f"  allow-list  {', '.join(settings.mcp_allowed_identities) or red('empty')}")
    else:
        say(f"  {dim('idle')}  {dim('- only needed for remote clients (nimkm mcp oauth)')}")
    return 0 if any_registered else NOTHING_CHANGED


def cmd_mcp_oauth(args: argparse.Namespace) -> int:
    """Configure the OAuth-protected HTTP connector for *remote* clients."""
    from app.core.config import get_settings

    settings = get_settings()
    base = settings.resolve_public_base_url() or _browsable_url(settings.host, settings.port)
    values = read_config()
    if not values:
        fail("no configuration found -- run 'nimkm init' first.")
        return 1

    provider = args.provider or values.get("MCP_AUTH_PROVIDER", "github")
    say(bold(f"Remote connector over HTTPS ({provider} OAuth)"))
    say(dim("Local clients do not need this -- use 'nimkm mcp setup' instead."))
    say()
    say(f"1. Create an OAuth app at {cyan(_oauth_console(provider))}")
    say(f"2. Set the callback URL to {cyan(base + '/auth/callback')}")
    say("3. Paste the credentials below.")
    say()
    client_id = args.client_id or (_ask("Client ID: ") or "").strip()
    client_secret = args.client_secret or _ask_secret("Client secret: ")
    identities = args.allow or (_ask("Allowed identities (comma separated): ") or "").strip()
    if not (client_id and client_secret and identities):
        fail("client id, secret and at least one allowed identity are required")
        return 1

    values["MCP_AUTH_PROVIDER"] = provider
    values[f"MCP_{provider.upper()}_CLIENT_ID"] = client_id
    values[f"MCP_{provider.upper()}_CLIENT_SECRET"] = client_secret
    values["MCP_ALLOWED_IDENTITIES"] = identities
    write_config(values)
    say()
    ok("remote connector configured")
    say(f"  endpoint  {cyan(base + settings.mcp_mount_path)}")
    say(dim("  start it with 'nimkm web' and add the URL as a custom connector"))
    return 0


def _ask_secret(prompt: str) -> str:
    if not _interactive():
        return ""
    try:
        return getpass.getpass(prompt).strip()
    except (EOFError, KeyboardInterrupt):
        return ""


def _confirm(question: str, default: bool = True, assume_yes: bool = False) -> bool:
    if assume_yes:
        say(f"{question} {dim('yes')}")
        return True
    if not _interactive():
        say(f"{question} {dim('skipped (no terminal to ask on; use --yes)')}")
        return False
    suffix = "[Y/n]" if default else "[y/N]"
    answer = _ask(f"{question} {suffix} ")
    if answer is None:  # the prompt was shown but nobody could answer it
        say(dim("  no answer -- skipped (use --yes to accept unattended)"))
        return False
    answer = answer.strip().lower()
    if not answer:
        return default
    return answer in ("y", "yes")


def _oauth_console(provider: str) -> str:
    return {
        "github": "https://github.com/settings/developers",
        "google": "https://console.cloud.google.com/apis/credentials",
    }.get(provider, "the provider console")


def cmd_update(args: argparse.Namespace) -> int:
    spec = _resolve_latest_spec()
    if spec is None:
        fail("could not determine the latest version (no network?)")
        return 1
    version, source = spec
    if version == __version__ and not args.force:
        ok(f"already on the latest version ({__version__})")
        return 0

    managed = _managed_python()
    if managed is None:
        say(f"A newer version is available: {bold(version)} (current {__version__})")
        say()
        say("This copy was not installed by the official installer. Update it with:")
        say(f"  {bold('pip install --upgrade ' + PYPI_PACKAGE)}")
        say(f"  {dim('or re-run the installer from ' + DOCS_URL)}")
        return 0

    step(f"updating {__version__} -> {version}")
    result = subprocess.call(
        [str(managed), "-m", "pip", "install", "--upgrade", "-q", source]
    )
    if result != 0:
        fail("update failed")
        return result
    ok(f"updated to {version}. Run 'nimkm migrate' if the release adds migrations.")
    return 0


def _managed_python() -> Path | None:
    """Interpreter of the installer-managed virtualenv, if this is one."""
    venv = paths.runtime_dir() / "venv"
    candidate = venv / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
    if candidate.exists() and Path(sys.prefix).resolve() == venv.resolve():
        return candidate
    return None


#: Hosts an update may be downloaded from. The URL comes from an API response,
#: so it is treated as untrusted input: whatever it says, we only ever fetch
#: from these, and only over HTTPS.
_TRUSTED_DOWNLOAD_HOSTS = frozenset({"github.com", "objects.githubusercontent.com"})


def _is_trusted_download(url: str) -> bool:
    from urllib.parse import urlparse

    parsed = urlparse(url)
    return parsed.scheme == "https" and parsed.hostname in _TRUSTED_DOWNLOAD_HOSTS


def _resolve_latest_spec() -> tuple[str, str] | None:
    """Return ``(version, pip-installable-source)`` for the newest release."""
    try:
        release = _http_json(f"https://api.github.com/repos/{REPO}/releases/latest")
        version = str(release.get("tag_name", "")).lstrip("v")
        for asset in release.get("assets", []):
            name = asset.get("name", "")
            url = asset.get("browser_download_url", "")
            if name.endswith(".whl") and _is_trusted_download(url):
                return version, url
        if version:
            return version, f"{PYPI_PACKAGE}=={version}"
    except Exception:  # noqa: BLE001 - fall through to PyPI
        pass
    try:
        data = _http_json(f"https://pypi.org/pypi/{PYPI_PACKAGE}/json")
        return str(data["info"]["version"]), PYPI_PACKAGE
    except Exception:  # noqa: BLE001
        return None


def cmd_uninstall(args: argparse.Namespace) -> int:
    home = paths.home()
    say(bold("This will remove:"))
    say(f"  runtime  {paths.runtime_dir()}")
    say(f"  shims    {paths.bin_dir()}")
    if args.purge:
        say(f"  config   {paths.config_file()}")
        say(f"  data     {paths.data_dir()} {red('(your encrypted keys!)')}")
    else:
        say(dim(f"  keeping configuration and data in {home} (use --purge to delete)"))
    say()
    if not args.yes:
        if not _interactive():
            fail("refusing to uninstall non-interactively without --yes")
            return 1
        if input("Type 'yes' to continue: ").strip().lower() != "yes":
            say("aborted")
            return 1

    targets = [paths.bin_dir(), paths.runtime_dir()]
    if args.purge:
        targets += [paths.config_file(), paths.data_dir(), paths.logs_dir()]
    leftovers = []
    for target in targets:
        try:
            if target.is_dir():
                shutil.rmtree(target, ignore_errors=False)
            elif target.exists():
                target.unlink()
        except OSError:
            leftovers.append(target)

    if args.purge and not leftovers and home.exists():
        try:
            shutil.rmtree(home)
        except OSError:
            leftovers.append(home)

    if leftovers:
        warn("some files are still in use (you are running from inside them).")
        say("Close this process and delete manually:")
        for target in leftovers:
            say(f"  {target}")
    else:
        ok("uninstalled")
    say(dim("Remember to remove the PATH entry from your shell profile if you added one."))
    return 0


def cmd_version(args: argparse.Namespace) -> int:
    say(f"nimkm {__version__}")
    if args.verbose:
        say(f"  runtime   {sys.version.split()[0]}")
        say(f"  home      {paths.home()}")
        say(f"  platform  {sys.platform}")
        say(f"  mcp       {_launcher_or_none() or '(launcher not found)'} mcp serve")
    return 0


# --------------------------------------------------------------------------- #
# argument parsing                                                             #
# --------------------------------------------------------------------------- #


def clients_default_name() -> str:
    from app.mcp.clients import DEFAULT_SERVER_NAME

    return DEFAULT_SERVER_NAME


def _print_help(parser: argparse.ArgumentParser) -> int:
    parser.print_help()
    return 0


def _add_setup_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--scope", choices=["user", "project", "desktop"],
        help="user: all your projects · project: ./.mcp.json · desktop: Claude Desktop",
    )
    parser.add_argument("--name", default=clients_default_name(), help="name shown to the client")
    parser.add_argument("--yes", action="store_true", help="do not ask for confirmation")
    parser.add_argument(
        "--print", dest="print_config", action="store_true",
        help="print the JSON to paste into any other MCP client",
    )


EPILOG = f"""\
getting started:
  nimkm mcp setup              connect this server to your MCP client
  nimkm mcp status             where it is registered, and as what

everyday use:
  nimkm doctor                 diagnose an installation
  nimkm web                    open the administration dashboard
  nimkm admin reset-password --email you@example.com
  nimkm update                 upgrade to the latest release

Your MCP client runs 'nimkm mcp serve' for you; you never have to.

docs: {DOCS_URL}
"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="nimkm",
        description=(
            "MCP server for the API keys of your own NVIDIA Build/NIM account: "
            "list, dispense, register, rotate and revoke keys from your AI client, "
            "with encrypted storage, roles and a full audit trail."
        ),
        epilog=EPILOG,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("-V", "--version", action="version", version=f"nimkm {__version__}")
    sub = parser.add_subparsers(dest="command")

    # --- MCP: the primary surface ------------------------------------------
    mcp = sub.add_parser(
        "mcp",
        help="connect to MCP clients, and serve them",
        description="Everything about talking MCP.",
    )
    mcp_sub = mcp.add_subparsers(dest="action")
    mcp.set_defaults(func=lambda _args: _print_help(mcp))

    mcp_setup = mcp_sub.add_parser("setup", help="register this server with your MCP client")
    _add_setup_arguments(mcp_setup)
    mcp_setup.set_defaults(func=cmd_mcp_setup)

    mcp_serve = mcp_sub.add_parser(
        "serve",
        help="speak MCP over stdio (your client runs this; you normally do not)",
    )
    mcp_serve.add_argument("--identity", help="act as this account instead of the local one")
    mcp_serve.set_defaults(func=cmd_mcp_serve)

    mcp_status = mcp_sub.add_parser("status", help="show where the server is registered")
    mcp_status.add_argument("--name", default=clients_default_name())
    mcp_status.set_defaults(func=cmd_mcp_status)

    mcp_remove = mcp_sub.add_parser("remove", help="unregister from MCP clients")
    mcp_remove.add_argument("--scope", choices=["user", "project", "desktop"])
    mcp_remove.add_argument("--name", default=clients_default_name())
    mcp_remove.add_argument("--yes", action="store_true")
    mcp_remove.set_defaults(func=cmd_mcp_remove)

    mcp_oauth = mcp_sub.add_parser(
        "oauth", help="configure the remote HTTPS connector (advanced)"
    )
    mcp_oauth.add_argument("--provider", choices=["github", "google"])
    mcp_oauth.add_argument("--client-id")
    mcp_oauth.add_argument("--client-secret")
    mcp_oauth.add_argument("--allow", help="comma-separated identities allowed to connect")
    mcp_oauth.set_defaults(func=cmd_mcp_oauth)

    # `nimkm setup` is the same thing: it is the first command anyone runs.
    setup = sub.add_parser("setup", help="alias for 'nimkm mcp setup'")
    _add_setup_arguments(setup)
    setup.set_defaults(func=cmd_mcp_setup)

    up = sub.add_parser("up", help="initialise (first run) and open the dashboard")
    up.add_argument("--host")
    up.add_argument("--port", type=int)
    up.add_argument("--no-browser", action="store_true", help="do not open a browser")
    up.add_argument("--no-input", action="store_true", help="never prompt")
    up.set_defaults(func=cmd_up)

    init = sub.add_parser("init", help="generate configuration, migrate and create the admin")
    init.add_argument(
        "--force", action="store_true",
        help="regenerate the configuration (backs up the old one; keeps the encryption key)",
    )
    init.add_argument("--host", default="127.0.0.1")
    init.add_argument("--port", type=int, default=8000)
    init.add_argument("--database-url", help="use PostgreSQL instead of the bundled SQLite")
    init.add_argument("--admin-email")
    init.add_argument("--admin-password")
    init.add_argument("--no-input", action="store_true", help="never prompt; generate defaults")
    init.set_defaults(func=cmd_init, quiet_next_step=False)

    web = sub.add_parser(
        "web", aliases=["serve"],
        help="run the administration dashboard and REST API",
    )
    web.add_argument("--host")
    web.add_argument("--port", type=int)
    web.add_argument("--reload", action="store_true", help="auto-reload (development)")
    web.add_argument("--proxy-headers", action="store_true", help="trust X-Forwarded-* headers")
    web.set_defaults(func=cmd_serve)

    migrate = sub.add_parser("migrate", help="apply database migrations")
    migrate.add_argument("revision", nargs="?", default="head")
    migrate.add_argument("--downgrade", action="store_true")
    migrate.set_defaults(func=cmd_migrate)

    doctor = sub.add_parser("doctor", help="diagnose configuration, database and connectivity")
    doctor.add_argument("--offline", action="store_true", help="skip network checks")
    doctor.set_defaults(func=cmd_doctor)

    status = sub.add_parser("status", help="MCP registration and dashboard state")
    status.add_argument("--name", default=clients_default_name())
    status.set_defaults(func=cmd_status)

    config = sub.add_parser("config", help="inspect or change configuration")
    config.add_argument("action", choices=["path", "show", "set", "edit"])
    config.add_argument("assignments", nargs="*", metavar="KEY=VALUE")
    config.set_defaults(func=cmd_config)

    admin = sub.add_parser("admin", help="manage administrator accounts")
    admin.add_argument("action", choices=["list", "create", "reset-password"])
    admin.add_argument("--email")
    admin.add_argument("--password", help="omit to generate a strong one")
    admin.add_argument("--name")
    admin.add_argument("--role", default="admin", choices=["admin", "manager", "viewer"])
    admin.add_argument("--actor", help="e-mail of an existing admin (when users already exist)")
    admin.set_defaults(func=cmd_admin)

    update = sub.add_parser("update", help="upgrade to the latest release")
    update.add_argument("--force", action="store_true")
    update.set_defaults(func=cmd_update)

    uninstall = sub.add_parser("uninstall", help="remove this installation")
    uninstall.add_argument("--purge", action="store_true", help="also delete config and data")
    uninstall.add_argument("--yes", action="store_true")
    uninstall.set_defaults(func=cmd_uninstall)

    version = sub.add_parser("version", help="show version information")
    version.add_argument("-v", "--verbose", action="store_true")
    version.set_defaults(func=cmd_version)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if getattr(args, "func", None) is None:
        parser.print_help()
        return 0
    if args.command == "admin" and args.action in ("create", "reset-password") and not args.email:
        parser.error(f"admin {args.action} requires --email")
    try:
        return int(args.func(args))
    except KeyboardInterrupt:
        say()
        say(dim("stopped"))
        return 130
    except Exception as exc:  # noqa: BLE001 - the CLI reports, it does not traceback
        if os.environ.get("NIMKM_DEBUG"):
            raise
        fail(f"{type(exc).__name__}: {exc}")
        say(dim("run with NIMKM_DEBUG=1 for the full traceback, or 'nimkm doctor'"))
        return 1


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
