"""Envelope encryption for stored API keys (AES-256-GCM, HKDF-derived key)."""

from __future__ import annotations

import base64
import hashlib
import os

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

from app.domain.exceptions import DecryptionError

_VERSION = "v1"
_HKDF_SALT = b"nim-key-manager.encryption.v1"
_HKDF_INFO = b"api-key-encryption"


class SecretCipher:
    """Encrypts/decrypts secrets with AES-256-GCM.

    The 256-bit data key is derived from an arbitrary master secret via
    HKDF-SHA256, so the master secret can be any random string (e.g. a
    value generated by the platform's secret manager).
    """

    def __init__(self, master_secret: str) -> None:
        kdf = HKDF(algorithm=hashes.SHA256(), length=32, salt=_HKDF_SALT, info=_HKDF_INFO)
        self._aesgcm = AESGCM(kdf.derive(master_secret.encode("utf-8")))

    def encrypt(self, plaintext: str) -> str:
        nonce = os.urandom(12)
        ciphertext = self._aesgcm.encrypt(nonce, plaintext.encode("utf-8"), None)
        return "$".join(("enc", _VERSION, _b64e(nonce), _b64e(ciphertext)))

    def decrypt(self, token: str) -> str:
        try:
            prefix, version, nonce_b64, ct_b64 = token.split("$")
            if prefix != "enc" or version != _VERSION:
                raise ValueError("unsupported token format")
            plaintext = self._aesgcm.decrypt(_b64d(nonce_b64), _b64d(ct_b64), None)
        except (ValueError, InvalidTag) as exc:
            raise DecryptionError("stored secret could not be decrypted") from exc
        return plaintext.decode("utf-8")


def fingerprint(plaintext: str) -> str:
    """Deterministic SHA-256 fingerprint used for duplicate detection."""
    return hashlib.sha256(plaintext.encode("utf-8")).hexdigest()


def hint(plaintext: str) -> str:
    """Non-sensitive display hint (never reveals the full secret)."""
    return f"…{plaintext[-4:]}" if len(plaintext) >= 8 else "…"


def _b64e(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).decode("ascii")


def _b64d(data: str) -> bytes:
    return base64.urlsafe_b64decode(data.encode("ascii"))
